ID: 'UN3-VAE3'
Dataset:
  data_path: '/scratch/snx3000/acarpent/HelioMontDataset/'
  n_in: 4
  n_out: 8
  batch_size: 20
  num_workers: 24
  train_length:
  val_length:
  norm_method: 'rescaling'
  min: 0.05
  max: 1.2
  mean: 0.6
  std: 0.3

Encoder:
  in_dim: 1
  levels: 2
  min_ch: 64
  max_ch: 128

Decoder: # not used at the moment (symmetrical architecture)
  in_dim: 1
  levels: 2
  min_ch: 64
  max_ch: 128

VAE:
  kl_weight: 0.01
  hidden_width: 32 # arbitrary value
  path: '/scratch/snx3000/acarpent/VAETrainingLogs/VAE3-CF=2-l=12_epoch=110-val_rec_loss=0.01699-val_kl_loss=1.88702.ckpt'

Nowcaster:
  embed_dim: 256
  forecast_depth: 6
  analysis_depth: 6
  input_steps: 1
  output_steps: 4
  opt_patience: 5
  loss_type: 'latent'
 
EarlyStopping:
  patience: 10

Checkpoint:
  dirpath: '/scratch/snx3000/acarpent/NowcasterTrainingLogs/'
  filename: '{epoch}-{val_loss:.5f}'
  monitor: 'val_loss'
  every_n_epochs: 1
  save_top_k: 3

Trainer:
  accelerator: 'gpu'
  precision: 16
  devices: 1
  max_epochs: 1000
  strategy: 'ddp'
  accumulate_grad_batches: 1
  resume_training:
